"""initial schema

Revision ID: 7ed522b53537
Revises: 
Create Date: 2026-06-20 10:18:54.657398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ed522b53537'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS ledger")
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('kyc_status', sa.Enum('verified', 'pending', 'failed', name='kyc_status', schema='core'), server_default='pending', nullable=False),
    sa.Column('country', sa.CHAR(length=2), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    schema='core'
    )
    op.create_table('entries',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='direction', schema='ledger'), nullable=False),
    sa.Column('amount', app.db.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('posted_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reversal_of', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_entries_amount_positive')),
    sa.ForeignKeyConstraint(['reversal_of'], ['ledger.entries.entry_id'], name=op.f('fk_entries_reversal_of_entries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('pk_entries')),
    schema='ledger'
    )
    op.create_index('ix_entries_account_id_posted_at', 'entries', ['account_id', 'posted_at'], unique=False, schema='ledger')
    op.create_index('ix_entries_transaction_id', 'entries', ['transaction_id'], unique=False, schema='ledger')
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.Text(), nullable=True),
    sa.Column('amount', app.db.types.Money(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('card', 'bank_transfer', 'wallet', 'upi', name='payment_method', schema='core'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'flagged', 'reversed', name='txn_status', schema='core'), server_default='pending', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('fraud_score', app.db.types.Money(precision=18, scale=4), nullable=True),
    sa.Column('chargeback_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('settlement_status', sa.Enum('settled', 'pending', 'disputed', 'reversed', name='settle_status', schema='core'), server_default='pending', nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('kyc_status_at_time', sa.Enum('verified', 'pending', 'failed', name='kyc_status', schema='core'), nullable=True),
    sa.Column('country_sender', sa.CHAR(length=2), nullable=True),
    sa.Column('country_receiver', sa.CHAR(length=2), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('fx_quote_id', sa.UUID(), nullable=True),
    sa.Column('parent_transaction', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_amount_positive')),
    sa.CheckConstraint('fraud_score IS NULL OR (fraud_score >= 0 AND fraud_score <= 1)', name=op.f('ck_transactions_fraud_score_range')),
    sa.ForeignKeyConstraint(['parent_transaction'], ['core.transactions.transaction_id'], name=op.f('fk_transactions_parent_transaction_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.user_id'], name=op.f('fk_transactions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_transactions_merchant_id_idempotency_key'),
    schema='core'
    )
    op.create_index('ix_transactions_merchant_id_created_at', 'transactions', ['merchant_id', sa.literal_column('created_at DESC')], unique=False, schema='core')
    op.create_index('ix_transactions_metadata_gin', 'transactions', ['metadata'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('ix_transactions_parent_partial', 'transactions', ['parent_transaction'], unique=False, schema='core', postgresql_where=sa.text('parent_transaction IS NOT NULL'))
    op.create_index('ix_transactions_settlement_partial', 'transactions', ['merchant_id', 'settlement_status'], unique=False, schema='core', postgresql_where=sa.text("settlement_status IN ('pending', 'disputed')"))
    op.create_index('ix_transactions_status_partial', 'transactions', ['status', 'created_at'], unique=False, schema='core', postgresql_where=sa.text("status IN ('flagged', 'failed')"))
    op.create_index('ix_transactions_user_id_created_at', 'transactions', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='core')
    op.create_table('wallets',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('balance', app.db.types.Money(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_wallets_balance_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.user_id'], name=op.f('fk_wallets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('wallet_id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('user_id', 'currency', name='uq_wallets_user_id_currency'),
    schema='core'
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets', schema='core')
    op.drop_table('wallets', schema='core')
    op.drop_index('ix_transactions_user_id_created_at', table_name='transactions', schema='core')
    op.drop_index('ix_transactions_status_partial', table_name='transactions', schema='core', postgresql_where=sa.text("status IN ('flagged', 'failed')"))
    op.drop_index('ix_transactions_settlement_partial', table_name='transactions', schema='core', postgresql_where=sa.text("settlement_status IN ('pending', 'disputed')"))
    op.drop_index('ix_transactions_parent_partial', table_name='transactions', schema='core', postgresql_where=sa.text('parent_transaction IS NOT NULL'))
    op.drop_index('ix_transactions_metadata_gin', table_name='transactions', schema='core', postgresql_using='gin')
    op.drop_index('ix_transactions_merchant_id_created_at', table_name='transactions', schema='core')
    op.drop_table('transactions', schema='core')
    op.drop_index('ix_entries_transaction_id', table_name='entries', schema='ledger')
    op.drop_index('ix_entries_account_id_posted_at', table_name='entries', schema='ledger')
    op.drop_table('entries', schema='ledger')
    op.drop_table('users', schema='core')
    # ### end Alembic commands ###
